FROM java

LABEL maintainer "misha"

COPY /project/target/HelloWorld-0.0.1-SNAPSHOT.jar /usr/src/myapp/HelloWorld-0.0.1-SNAPSHOT.jar

WORKDIR /usr/src/myapp/

ENTRYPOINT java -jar HelloWorld-0.0.1-SNAPSHOT.jar
